#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# SPDX-License-Identifier: CC0-1.0
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# This wizard captures no values: the pipeline has no secrets and no .env.
# Every stage is a pure action against GitHub. If a source ever needs a
# credential, add a stage here (ask_secret + set_secret) AND a matching
# `secrets.*` reference in .github/workflows/publish-feeds.yml — those two
# must always agree.

REPO="jennymaeleidig/news-digest-agent"
SITE="https://jennymaeleidig.github.io/news-digest-agent/"
WORKFLOW="publish-feeds.yml"
ACTIONS_URL="https://github.com/$REPO/actions/workflows/$WORKFLOW"
PAGES_SETTINGS_URL="https://github.com/$REPO/settings/pages"

has_gh() { command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; }

TOTAL_STAGES=5

banner "Publish the source log to GitHub Pages"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Repo and tooling"
say "Checks this is the right checkout and that the GitHub CLI can act for you."

if [[ ! -f sources.toml || ! -d feeds ]]; then
  warn "run this from the repo root (sources.toml and feeds/ not found here)"
  exit 1
fi
say "repo: $(pwd)"

branch=$(git rev-parse --abbrev-ref HEAD)
say "branch: $branch"
if [[ "$branch" != "main" ]]; then
  warn "the workflow only publishes from main, and you're on $branch"
  if confirm "switch to main now?"; then git switch main; fi
fi

if has_gh; then
  say "gh: authenticated as $(gh api user --jq .login 2>/dev/null || echo '?')"
else
  warn "gh is missing or not logged in — stages 2, 4 and 5 will fall back to the browser"
  note "to fix: brew install gh && gh auth login"
fi
pause

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "GitHub Pages: build from Actions"
say "The site is served by the Actions artifact, not a branch. Idempotent:"
say "if it's already enabled this stage does nothing."

enabled=""
if has_gh; then
  enabled=$(gh api "repos/$REPO/pages" --jq '.build_type' 2>/dev/null || true)
fi

if [[ "$enabled" == "workflow" ]]; then
  say "already enabled (build_type=workflow) — nothing to do"
elif has_gh; then
  if gh api -X POST "repos/$REPO/pages" -f "build_type=workflow" >/dev/null 2>&1; then
    say "enabled: Pages now builds from GitHub Actions"
    note "site: $SITE (HTTPS enforced by GitHub)"
  else
    warn "couldn't enable Pages via the API — do it in the browser"
    enabled=""
  fi
fi

if [[ "$enabled" != "workflow" ]]; then
  open_url "$PAGES_SETTINGS_URL"
  step "Under 'Build and deployment', set Source to 'GitHub Actions'."
  step "Leave the branch/path fields alone — they disappear once Source is Actions."
  pause "Press Enter once Source reads 'GitHub Actions'"
fi

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Push main"
say "The push is what publishes: it triggers the workflow, which tests,"
say "generates the site from sources.toml, and deploys the artifact."

if ! git rev-parse --verify --quiet '@{u}' >/dev/null; then
  warn "no upstream is set for this branch"
  if confirm "push and set upstream to origin/main?"; then git push -u origin main; fi
else
  ahead=$(git rev-list --count '@{u}..HEAD')
  if [[ "$ahead" == "0" ]]; then
    say "nothing to push — origin/main already has your commits"
  else
    say "commits to push: $ahead"
    git --no-pager log --oneline '@{u}..HEAD' | sed 's/^/    /'
    note "the push deletes the digest workflows from GitHub and adds publish-feeds"
    if confirm "push to origin/main now?"; then
      git push origin main
    else
      warn "skipped — nothing below will show new content until this happens"
    fi
  fi
fi
pause

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Verify the published site"
say "The workflow takes a minute or two; then the feeds are live at:"
say "  $SITE"
say "  ${SITE}opml.xml"

if has_gh; then
  run_id=$(gh run list --workflow="$WORKFLOW" --limit 1 --json databaseId --jq '.[0].databaseId' 2>/dev/null || true)
  if [[ -n "$run_id" ]]; then
    status=$(gh run view "$run_id" --json status,conclusion --jq '.status + " " + (.conclusion // "-")' 2>/dev/null || echo "?")
    say "latest run: $status"
    if confirm "watch it to completion (gh run watch)?"; then
      gh run watch "$run_id" --exit-status || warn "the run reported a failure — the log is in Actions"
    fi
  else
    warn "no run found for $WORKFLOW yet"
  fi
  open_url "$ACTIONS_URL"
fi

if command -v curl >/dev/null 2>&1; then
  if curl -sfI "${SITE}opml.xml" >/dev/null 2>&1; then
    say "live check: ${SITE}opml.xml responds ✓"
  else
    warn "opml.xml isn't serving yet — give the run a minute, then re-check"
  fi
else
  pause "Open the site in the browser and confirm the feeds and OPML load"
fi
open_url "$SITE"

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Only if the feeds ever go quiet"
say "GitHub disables scheduled workflows after 60 days of no repo activity."
say "The fix is to re-enable it — no reconfiguration, no data loss; the next"
say "run merges upstream items with the feeds already published."

state=""
if has_gh; then
  state=$(gh api "repos/$REPO/actions/workflows" \
    --jq ".workflows[] | select(.path | endswith(\"$WORKFLOW\")) | .state" 2>/dev/null || true)
  say "workflow state: ${state:-unknown}"
fi

if [[ "$state" == "active" ]]; then
  say "active — nothing to do; this page is here for the day it isn't"
elif [[ "$state" == disabled_* ]]; then
  if has_gh; then
    if confirm "re-enable $WORKFLOW now?"; then gh workflow enable "$WORKFLOW"; fi
  fi
  open_url "$ACTIONS_URL"
  step "Click 'Enable workflow'."
else
  note "if Actions shows it disabled, enable it from the workflow page:"
  note "  $ACTIONS_URL"
fi
pause

finish
note "Published site: $SITE"
note "Operations notes: README → Operations."
